### ISSUE TITLE
Resurfacing a Question (Jetty & v6)

### ISSUE THREAD

**Issue by codeclout** [cantaloupe-project/cantaloupe#614] opened 2022-11-08 18:20 UTC
Hi,

I just took a look at the development branch of this repository and found that Jetty is being upgraded in v6. Is there a timetable as to when v6 will be available? If there is no known timetable on a v6 release, is there a way to update Jetty without recompiling from source?

Thanks in Advance,
~Brian

**Comment by bencomp** [comment] 2023-02-01 14:30
This is a duplicate of #611 – which is a good question. To focus the efforts, I feel it helps to keep questions/discussions in one thread or issue. Would you mind closing this?

**Closed as completed** 2023-02-01 20:23 UTC
