### ISSUE TITLE
IIIF v3 'max' image implementation is incorrect

### ISSUE THREAD

**Issue by cmhdave** [cantaloupe-project/cantaloupe#426] opened 2021-01-08 13:39 UTC
I have restricted my `max_pixels` setting in my `cantaloupe.properties` file to 100000000 and added an image that is LARGER than that.  When requesting the image with `/full/max/0/default.jpg` from the `iiif/3/` endpoint I get a 403 error that "The requested pixel area exceeds the maximum threshold set in the configuration."

This is incorrect according to Rob Sanderson in the IIIF community.

https://github.com/IIIF/api/issues/1909#issuecomment-613039172

> Yes, full/max will return the full region of the image, downscaled to max height.

Instead of throwing a 4xx error we should be serving up the largest possible image allowed by the `max_pixels` setting. It could be argued that `iiif/2` with `full/full` should have that same functionality though I don't have direct evidence that is the expected behavior from the IIIF community

**Comment by cmhdave** [comment] 2021-01-08 22:46
I did a little simple algebra to find the `width` x `height` based on a `max_pixels` setting.   Let's make some assumptions first

- Area (A) is `max_pixels`
- Aspect Ratio (R) is original image `width` / `height`

The formula then becomes
`(R * w) * w = A`
Simplified further
`w^2 = A/R`
Final width 
`w = sqrt(A/R)` 
Length is then easy to determine by 
`l = A/w`

**Comment by adolski** [comment] 2021-01-13 18:08
Thanks for reporting this, @cmhdave. It is now fixed in the v2 and v3 endpoints when using `max` size. (`full` size in v1 & v2 are unchanged.) I'm going to leave it unfixed in 4.1.x because it's something most users probably won't encounter, and 5.0 isn't far away.

**Closed as completed by adolski** 2021-01-13 18:08 UTC
Labels: bug

**Comment by cmhdave** [comment] 2021-01-21 16:01
I have the latest `develop` build deployed to my test environment and it seems as though the `/max` setting isn't quite working.  When I test with an image that is greater than my max_pixels setting it renders rather strangely
![github426](https://user-images.githubusercontent.com/32506/105376455-c5d37d00-5bd7-11eb-85ae-ae221cff4325.png)

The tiles additionally look strange when viewing the image in OpenSeadragon
![github426-2](https://user-images.githubusercontent.com/32506/105376654-f7e4df00-5bd7-11eb-8a60-243954096ee3.png)

**Comment by adolski** [comment] 2021-01-22 14:53
Can you provide more information about source image, processor, and image URI?

**Comment by cmhdave** [comment] 2021-01-22 15:31
Ah, interesting point.  The source image is a JP2 and we're using Kakadu (we have version 8.0.6 currently running).  The image URL can be /sample.jp2/full/max/0/default.jpg or even some of the smaller tiles (but not the smallest tiles, those seem to work ok)

It should be noted that when I reinstall the previous version the image tiles work fine with the same setup.

**Comment by adolski** [comment] 2021-01-22 19:10
I can't reproduce. I don't think this is related to the max change, but I have a hunch what it is related to. Could you post your source image somewhere where I can download it?

**Comment by cmhdave** [comment] 2021-01-22 20:14
Sure can.

https://drive.google.com/file/d/1jJX6kBhntz4qNiZfoy2iE4u_Dtnkn2EW/view?usp=sharing

**Comment by adolski** [comment] 2021-01-22 20:35
Thanks @cmhdave, I recently made what I thought was an optimization in the Kakadu reader, and it worked with my images but not yours. So I just pushed revert of that onto `develop`.

**Comment by cmhdave** [comment] 2021-01-22 21:02
This is great, works like a charm now @adolski !
