### ISSUE TITLE
Invalid call to `kdu_sample_allocator::release'

### ISSUE THREAD

**Issue by cbeer** [cantaloupe-project/cantaloupe#351] opened 2020-02-27 00:53 UTC
[This JP2](https://stacks.stanford.edu/file/druid:fk760gd3725/fk760gd3725_00_0001.jp2)(50M, 20747x13917)   seems to consistently crash cantaloupe 4.1.5 with the error when generating a full-size derivative (e.g. /iiif/2/fk760gd3725_00_0001.jp2/full/20747,/0/default.jpg).

```
Error:
Invalid call to `kdu_sample_allocator::release'.  Allocator must be in the
pre-allocation state with nothing pre-allocated.
```

Here's a full debug  trace:
```
16:52:18.514 [qtp434176574-18] DEBUG e.i.l.c.s.FilesystemSource - Resolved fk760gd3725_00_0001.jp2 to /Users/cabeer/fk760gd3725_00_0001.jp2
16:52:18.548 [qtp434176574-18] DEBUG e.i.l.c.p.ProcessorFactory - KakaduNativeProcessor selected for format JP2 (AutomaticSelectionStrategy offered KakaduNativeProcessor, OpenJpegProcessor, ImageMagickProcessor, GraphicsMagickProcessor)
16:52:18.550 [qtp434176574-18] DEBUG e.i.l.c.p.ProcessorConnector - FileSource -> FileProcessor connection between FilesystemSource and KakaduNativeProcessor
16:52:18.561 [qtp434176574-18] TRACE e.i.l.c.p.c.JPEG2000KakaduImageReader - readInfo(): read in 1 msec
16:52:18.562 [qtp434176574-18] DEBUG e.i.l.c.c.InfoService - readInfo(): read fk760gd3725_00_0001.jp2 from KakaduNativeProcessor in 11 msec
16:52:18.564 [qtp434176574-18] TRACE e.i.l.c.a.TaskRunner - submit(): edu.illinois.library.cantaloupe.cache.InfoService$$Lambda$74/1842176117@18bbea40 (queue size: 0)
16:52:18.564 [work-nm-4157675] TRACE e.i.l.c.a.TaskRunner - run(): running edu.illinois.library.cantaloupe.cache.InfoService$$Lambda$74/1842176117@18bbea40
16:52:18.565 [work-nm-4157675] DEBUG e.i.l.c.c.InfoService - putInObjectCache(): adding info: fk760gd3725_00_0001.jp2 (new size: 1)
16:52:18.565 [work-nm-4157675] DEBUG e.i.l.c.c.InfoCache - putInObjectCache(): adding info: fk760gd3725_00_0001.jp2 (new size: 1)
16:52:18.566 [qtp434176574-18] TRACE e.i.l.c.o.OperationList - applyNonEndpointMutations(): redactions are disabled; skipping.
16:52:18.570 [qtp434176574-18] TRACE e.i.l.c.o.OperationList - applyNonEndpointMutations(): overlays are disabled; skipping.
16:52:18.579 [qtp434176574-18] DEBUG e.i.l.c.r.i.v.ImageResource - Base URI assembled from X-Forwarded headers: http://127.0.0.1:8182
16:52:18.581 [qtp434176574-18] DEBUG e.i.l.c.r.ImageRepresentation - Derivative cache not available; writing directly to the response
16:52:18.583 [qtp434176574-18] DEBUG e.i.l.c.p.c.JPEG2000KakaduImageReader - Rendered region 0,0/20747x13917; source 0,0/20747x13917; 0x reduction factor; differential scale 10000000/10000000; PPI 600.0x600.0
16:52:24.250 [qtp434176574-18] TRACE e.i.l.c.p.c.JPEG2000KakaduImageReader - readRegion(): read in 5667 msec
16:52:24.260 [qtp434176574-18] DEBUG e.i.l.c.p.c.JPEGImageWriter - ImageIO plugin preferences: com.sun.imageio.plugins.jpeg.JPEGImageWriter
16:52:24.260 [qtp434176574-18] DEBUG e.i.l.c.p.c.JPEGImageWriter - Using com.sun.imageio.plugins.jpeg.JPEGImageWriter
16:52:25.876 [qtp434176574-18] DEBUG e.i.l.c.p.Java2DUtil - removeAlpha(): executed in 1604 msec
16:52:25.877 [qtp434176574-18] DEBUG e.i.l.c.p.c.JPEGImageWriter - Quality: 80; progressive: true
16:52:45.819 [qtp434176574-18] DEBUG e.i.l.c.r.ImageRepresentation - KakaduNativeProcessor processed in 27238 msec: fk760gd3725_00_0001.jp2_1:1_encode:jpg_JPEG_80_interlace_#FFFFFF_8
16:52:45.823 [qtp434176574-18] ERROR e.i.l.c.p.c.JPEG2000KakaduImageReader - Kakadu Core Error:
Invalid call to `kdu_sample_allocator::release'.  Allocator must be in the
pre-allocation state with nothing pre-allocated.

libc++abi.dylib: terminating with uncaught exception of type int
Abort trap: 6
```

**Comment by adolski** [comment] 2020-02-28 22:23
This smells like a bug that is internal to Kakadu, as `kdu_sample_allocator` is not used directly by Cantaloupe.

**Comment by cbeer** [comment] 2020-02-28 22:45
Yeah, I'm not sure what's going on. I traced it down to the destroy call at https://github.com/cantaloupe-project/cantaloupe/blob/develop/src/main/java/edu/illinois/library/cantaloupe/processor/codec/jpeg2000/JPEG2000KakaduImageReader.java#L270, but I'm not sure if rescuing it (like some of the other steps) is the right thing to do?

**Comment by adolski** [comment] 2020-03-04 22:13
This appears to no longer be an issue in the newest Kakadu version (8.0.3). It is still an issue in the latest 7.x version (7.10.7).

Really there are two problems here. One is the invocation of `Kdu_region_decompressor.Native_destroy()` leading ultimately to an errant (apparently) invocation of `kdu_sample_allocator::release()` (in native code). The other is that Kakadu's Java binding is supposed to enable kdu_errors to be caught as KduExceptions without the process exiting.

I would like to include Kakadu 8 in Cantaloupe 5 (#357). The migration involves only copying the new Kakadu class files into the `kdu_jni` package and installing new library binaries. This would probably all work fine in 4.x, but I don't want to introduce such a major change in a bugfix release. You are welcome to build your own custom 4.x, though.

I'll try to get #357 done and pushed up soon.

**Comment by cbeer** [comment] 2020-03-04 22:31
👍 ; as a weird data point, we've also found that changing the `JPEG2000KakaduImageReader.NUM_THREADS` from a calcuated 8 to 4 seems to make the allocator problem go away? 🤷‍♂

**Comment by adolski** [comment] 2020-03-04 22:35
That is interesting, I wonder if Kakadu is seeing fewer cores than Runtime?

**Comment by cbeer** [comment] 2020-03-04 22:52
It's very weird; and I guess it isn't just  changing it to 4, but somehow dependent on the image size. I guess we'll sit tight for Kakadu 8.

**Comment by adolski** [comment] 2020-03-20 20:24
Fixed on `develop` via #357

**Closed by adolski** 2020-03-20 20:24 UTC
Labels: bug

**Comment by cachemeoutside** [comment] 2021-06-10 18:07
Hi @adolski, I came across this issue recently with a 75MB jp2 source. I'm curious if you have more info on this.

I think our issue is that we're running Cantaloupe in a Kubernetes environment. While we set resource limits on the k8s level, the container still sees OS level info of the node it's running on. It seems that Kakadu would allocate threads based on what info is provided through the OS.

In our case our node has 8 cores, but we have a container CPU limit of 6 cores. The container still sees the full 8 cores from the node. This reproduces the issue described from OP. When we reduce the CPU limit to 4 cores, this appears to resolve the issue. I'm wondering if this is an issue with mapping threads to CPU. Not sure how Kakadu 8 would address this. Would be curious to know.

Thx!

**Comment by cachemeoutside** [comment] 2021-06-10 19:48
Here's what seems to be the linked logic: https://github.com/cantaloupe-project/cantaloupe/blob/release/4.1/src/main/java/edu/illinois/library/cantaloupe/processor/codec/JPEG2000KakaduImageReader.java#L459-L463

Since we're running in containers, it seems that we may have to set this to a static value. I guess my next steps are to see what the output of NUM_THREAD  to really see how many threads are created.

**Comment by cachemeoutside** [comment] 2021-06-10 21:35
After experimenting a bit more with `-XX:ActiveProcessorCount=6` which changes the visible cores to the JVM, it doesn't seem to like value greater than 4. I guess that's something Kakadu 8 may have addressed. I thought it might've been a conflict due to how many threads were created vs the limitation, but seems like that's no longer the case.

**Comment by adolski** [comment] 2021-06-15 20:00
@cachemeoutside Thanks for reporting your experiences with this. I don't have any more info, but I can replace `NUM_THREADS` with a configurable value if that would help.
