### ISSUE TITLE
HTTPSource AccessDeniedException from ExecutionException

### ISSUE THREAD

**Issue by adam-vessey** [cantaloupe-project/cantaloupe#273] opened 2019-03-14 21:25 UTC
We've run into issues on multiple servers running on Cantaloupe 4.0.3 on Tomcat, sporadically having somewhat unexplained HTTP 403 errors.

The stacktrace in the response starts with:
```
java.nio.file.AccessDeniedException: [... the URI ...]
    at edu.illinois.library.cantaloupe.source.HttpSource.fetchRangedGETResponse(HttpSource.java:422)
    at edu.illinois.library.cantaloupe.source.HttpSource.checkAccess(HttpSource.java:236)
    at edu.illinois.library.cantaloupe.resource.iiif.v2.InformationResource.doGet(InformationResource.java:98)
    at sun.reflect.GeneratedMethodAccessor81.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[...]
```

Pointing at [a line throwing a `AccessDeniedException` as when handling an `ExecutionException`](https://github.com/medusa-project/cantaloupe/blob/24d0e2074fa0feadf171718ea071cde188573c30/src/main/java/edu/illinois/library/cantaloupe/source/HttpSource.java#L422); however, it seems like it might be masking some underlying issue... as in, what's up with the `ExecutionException`?, kind of thing... 

Looking into ways to be able to get some info out... `AccessDeniedException`'s constructor does not accept a `Throwable` for a "cause", but there is the `initCause()` method which might be used... or it's possible that additional logging may suffice?

Both together, maybe something like?:
```diff
diff --git a/src/main/java/edu/illinois/library/cantaloupe/source/HttpSource.java b/src/main/java/edu/illinois/library/cantaloupe/source/HttpSource.java
index 078b799c2..c755c8f24 100644
--- a/src/main/java/edu/illinois/library/cantaloupe/source/HttpSource.java
+++ b/src/main/java/edu/illinois/library/cantaloupe/source/HttpSource.java
@@ -528,7 +528,17 @@ class HttpSource extends AbstractSource implements StreamSource {
         try {
             return request.send();
         } catch (ExecutionException e) {
-            throw new AccessDeniedException(requestInfo.getURI());
+            LOGGER.debug("ExecutionException from request.send(); generating AccessDeniedException.", e);
+
+            AccessDeniedException ade = new AccessDeniedException(requestInfo.getURI());
+            try {
+                // Attempt to add the cause of the exception, since it is not
+                // accepted by the constructor.
+                ade.initCause(e);
+            } catch (IllegalStateException ise) {
+                LOGGER.debug("Could not set exception cause.", ise);
+            }
+            throw ade;
         } catch (InterruptedException | TimeoutException e) {
             throw new IOException(e);
         }
```

Could throw together a PR with the above (or some subset); alternatively, thoughts on what might be happening? Unsure if it might be related, but the URI from the stacktrace above _is_ an HTTPS URL; however, it _is_ able to fetch the source sporadically... and a restart of Tomcat seems to clear the issue for a while...

**Comment by adolski** [comment] 2019-03-14 22:03
If it's a Jetty client bug, it wouldn't be the first one found by a Cantaloupe user. Another thing you could try is removing this:

https://github.com/medusa-project/cantaloupe/blob/1eb8459cd98c7d7c86bdf5942930645d3f3588cf/src/main/java/edu/illinois/library/cantaloupe/logging/ApplicationLogFilter.java#L25-L29

I should put a note in the class doc that I did that. That will give you a lot more information.

**Comment by adam-vessey** [comment] 2019-03-18 13:45
Threw in a PR (#274) adding minimal logging... given we're not sure what set of circumstances lead to this sporadic behaviour, I'm hesitant to go so verbose right now, but will keep it in mind.

**Comment by dxu1789** [comment] 2019-06-04 21:58
We're seeing this too in 4.1.1 Standalone mode when running a stress test using JMeter. It's fine to a certain point, but we start to see this error more and more when we get up to 50-100 concurrent threads constantly requesting. 

`2019-06-04 17:52:45,099 DEBUG [qtp2008017533-81] e.i.l.c.s.HttpSource [HttpSource.java:534] ExecutionException from Request.send(); generating AccessDeniedException.
java.util.concurrent.ExecutionException: java.net.ConnectException: Connection refused
	at org.eclipse.jetty.client.util.FutureResponseListener.getResult(FutureResponseListener.java:118)
	at org.eclipse.jetty.client.util.FutureResponseListener.get(FutureResponseListener.java:101)
	at org.eclipse.jetty.client.HttpRequest.send(HttpRequest.java:684)
	at edu.illinois.library.cantaloupe.source.HttpSource.request(HttpSource.java:532)
	at edu.illinois.library.cantaloupe.source.HttpSource.request(HttpSource.java:503)
	at edu.illinois.library.cantaloupe.source.HttpSource.fetchHEADResponseInfo(HttpSource.java:478)
	at edu.illinois.library.cantaloupe.source.HttpSource.checkAccess(HttpSource.java:304)
	at edu.illinois.library.cantaloupe.resource.iiif.v2.ImageResource.doGET(ImageResource.java:137)
	at edu.illinois.library.cantaloupe.resource.HandlerServlet.handle(HandlerServlet.java:96)
	at edu.illinois.library.cantaloupe.resource.HandlerServlet.doGet(HandlerServlet.java:34)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:857)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:535)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1340)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1242)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:503)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.eclipse.jetty.io.SelectorManager.doFinishConnect(SelectorManager.java:355)
	at org.eclipse.jetty.io.ManagedSelector.processConnect(ManagedSelector.java:207)
	at org.eclipse.jetty.io.ManagedSelector.access$1400(ManagedSelector.java:61)
	at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.processSelected(ManagedSelector.java:485)
	at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.produce(ManagedSelector.java:351)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produceTask(EatWhatYouKill.java:357)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:181)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	... 3 common frames omitted`

This is with chunking turned off. With chunking on the error is different:

`2019-06-04 17:53:21,448 ERROR [qtp2008017533-55] e.i.l.c.p.c.JPEG2000KakaduImageReader [JPEG2000KakaduImageReader.java:113] java.util.concurrent.ExecutionException: java.net.ConnectException: Connection refused
2019-06-04 17:53:21,448 ERROR [qtp2008017533-55] e.i.l.c.p.c.JPEG2000KakaduImageReader [JPEG2000KakaduImageReader.java:158] Kakadu Core Error:
Code-stream must start with an SOC marker!`

**Comment by kaij** [comment] 2019-06-09 20:29
Got a similar problem (Cantaloupe v4.1.2). Sporadic HTTP 408 or EOFExceptions, with medium parallel load (~>40 concurrent HTTPSource requests). It's quite reproducible manually, although writing a test script for high load would definitely take some time.

Checked the source server with httpry dump - requests don't come in, it seems the requests never leave cantaloupe. In the cantaloupe log, I see the exception below (sorry for the encoding).

It's independed of processor (here: Java2d, but also tested streaming TurboJpeg) and caching (here: no caching). Never tried chunking because the source does not support it. Depending on which request failed (HEAD or GET, the message differs - HEAD requests have the message from https://github.com/cantaloupe-project/cantaloupe/issues/273#issuecomment-498859010

Images will fail if the server gets under a little load. It's not highly critical because next request to the image will just deliver - but it is still quite a problem.

It seems the error is happening here:
```org.eclipse.jetty.client.http.HttpReceiverOverHTTP.earlyEOF(HttpReceiverOverHTTP.java:338)```

Any ideas what I could check or do? Is it possible to hook another Http Client library?

```
java.util.concurrent.ExecutionException: java.io.EOFException: HttpConnectionOverHTTP@70c99290::SocketChannelEndPoint@35483798{multivio/10.0.0.5:80&#60;-&#62;/10.0.0.6:60336,ISHUT,fill=-,flush=-,to=0/0}{io=1/0,kio=1,kro=1}-&#62;HttpConnectionOverHTTP@70c99290(l:/10.0.0.6:60336 &#60;-&#62; r:multivio/10.0.0.5:80,closed=false)=&#62;HttpChannelOverHTTP@61a5c45f(exchange=HttpExchange@605a325a req=TERMINATED/null@null res=PENDING/null@null)[send=HttpSenderOverHTTP@49e6a94d(req=QUEUED,snd=COMPLETED,failure=null)[HttpGenerator@3de6b31e{s=START}],recv=HttpReceiverOverHTTP@72ae0fc1(rsp=IDLE,failure=null)[HttpParser{s=CLOSED,0 of -1}]]


java.io.IOException: java.util.concurrent.ExecutionException: java.io.EOFException: HttpConnectionOverHTTP@70c99290::SocketChannelEndPoint@35483798{multivio/10.0.0.5:80&#60;-&#62;/10.0.0.6:60336,ISHUT,fill=-,flush=-,to=0/0}{io=1/0,kio=1,kro=1}-&#62;HttpConnectionOverHTTP@70c99290(l:/10.0.0.6:60336 &#60;-&#62; r:multivio/10.0.0.5:80,closed=false)=&#62;HttpChannelOverHTTP@61a5c45f(exchange=HttpExchange@605a325a req=TERMINATED/null@null res=PENDING/null@null)[send=HttpSenderOverHTTP@49e6a94d(req=QUEUED,snd=COMPLETED,failure=null)[HttpGenerator@3de6b31e{s=START}],recv=HttpReceiverOverHTTP@72ae0fc1(rsp=IDLE,failure=null)[HttpParser{s=CLOSED,0 of -1}]]
	at edu.illinois.library.cantaloupe.resource.ImageRepresentation.copyOrProcess(ImageRepresentation.java:146)
	at edu.illinois.library.cantaloupe.resource.ImageRepresentation.write(ImageRepresentation.java:76)
	at edu.illinois.library.cantaloupe.resource.iiif.v2.ImageResource.doGET(ImageResource.java:212)
	at edu.illinois.library.cantaloupe.resource.HandlerServlet.handle(HandlerServlet.java:96)
	at edu.illinois.library.cantaloupe.resource.HandlerServlet.doGet(HandlerServlet.java:34)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:865)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:542)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1700)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1667)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:505)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:786)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:743)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: edu.illinois.library.cantaloupe.processor.ProcessorException: java.util.concurrent.ExecutionException: java.io.EOFException: HttpConnectionOverHTTP@70c99290::SocketChannelEndPoint@35483798{multivio/10.0.0.5:80&#60;-&#62;/10.0.0.6:60336,ISHUT,fill=-,flush=-,to=0/0}{io=1/0,kio=1,kro=1}-&#62;HttpConnectionOverHTTP@70c99290(l:/10.0.0.6:60336 &#60;-&#62; r:multivio/10.0.0.5:80,closed=false)=&#62;HttpChannelOverHTTP@61a5c45f(exchange=HttpExchange@605a325a req=TERMINATED/null@null res=PENDING/null@null)[send=HttpSenderOverHTTP@49e6a94d(req=QUEUED,snd=COMPLETED,failure=null)[HttpGenerator@3de6b31e{s=START}],recv=HttpReceiverOverHTTP@72ae0fc1(rsp=IDLE,failure=null)[HttpParser{s=CLOSED,0 of -1}]]
	at edu.illinois.library.cantaloupe.processor.Java2dProcessor.process(Java2dProcessor.java:70)
	at edu.illinois.library.cantaloupe.resource.ImageRepresentation.process(ImageRepresentation.java:177)
	at edu.illinois.library.cantaloupe.resource.ImageRepresentation.copyOrProcess(ImageRepresentation.java:144)
	... 31 more
Caused by: java.io.IOException: java.util.concurrent.ExecutionException: java.io.EOFException: HttpConnectionOverHTTP@70c99290::SocketChannelEndPoint@35483798{multivio/10.0.0.5:80&#60;-&#62;/10.0.0.6:60336,ISHUT,fill=-,flush=-,to=0/0}{io=1/0,kio=1,kro=1}-&#62;HttpConnectionOverHTTP@70c99290(l:/10.0.0.6:60336 &#60;-&#62; r:multivio/10.0.0.5:80,closed=false)=&#62;HttpChannelOverHTTP@61a5c45f(exchange=HttpExchange@605a325a req=TERMINATED/null@null res=PENDING/null@null)[send=HttpSenderOverHTTP@49e6a94d(req=QUEUED,snd=COMPLETED,failure=null)[HttpGenerator@3de6b31e{s=START}],recv=HttpReceiverOverHTTP@72ae0fc1(rsp=IDLE,failure=null)[HttpParser{s=CLOSED,0 of -1}]]
	at edu.illinois.library.cantaloupe.source.HTTPStreamFactory.newInputStream(HTTPStreamFactory.java:74)
	at edu.illinois.library.cantaloupe.processor.codec.AbstractIIOImageReader.setSource(AbstractIIOImageReader.java:313)
	at edu.illinois.library.cantaloupe.processor.codec.ImageReaderFactory.newImageReader(ImageReaderFactory.java:82)
	at edu.illinois.library.cantaloupe.processor.AbstractImageIOProcessor.getReader(AbstractImageIOProcessor.java:125)
	at edu.illinois.library.cantaloupe.processor.Java2dProcessor.process(Java2dProcessor.java:48)
	... 33 more
Caused by: java.util.concurrent.ExecutionException: java.io.EOFException: HttpConnectionOverHTTP@70c99290::SocketChannelEndPoint@35483798{multivio/10.0.0.5:80&#60;-&#62;/10.0.0.6:60336,ISHUT,fill=-,flush=-,to=0/0}{io=1/0,kio=1,kro=1}-&#62;HttpConnectionOverHTTP@70c99290(l:/10.0.0.6:60336 &#60;-&#62; r:multivio/10.0.0.5:80,closed=false)=&#62;HttpChannelOverHTTP@61a5c45f(exchange=HttpExchange@605a325a req=TERMINATED/null@null res=PENDING/null@null)[send=HttpSenderOverHTTP@49e6a94d(req=QUEUED,snd=COMPLETED,failure=null)[HttpGenerator@3de6b31e{s=START}],recv=HttpReceiverOverHTTP@72ae0fc1(rsp=IDLE,failure=null)[HttpParser{s=CLOSED,0 of -1}]]
	at org.eclipse.jetty.client.util.InputStreamResponseListener.get(InputStreamResponseListener.java:221)
	at edu.illinois.library.cantaloupe.source.HTTPStreamFactory.newInputStream(HTTPStreamFactory.java:67)
	... 37 more
Caused by: java.io.EOFException: HttpConnectionOverHTTP@70c99290::SocketChannelEndPoint@35483798{multivio/10.0.0.5:80&#60;-&#62;/10.0.0.6:60336,ISHUT,fill=-,flush=-,to=0/0}{io=1/0,kio=1,kro=1}-&#62;HttpConnectionOverHTTP@70c99290(l:/10.0.0.6:60336 &#60;-&#62; r:multivio/10.0.0.5:80,closed=false)=&#62;HttpChannelOverHTTP@61a5c45f(exchange=HttpExchange@605a325a req=TERMINATED/null@null res=PENDING/null@null)[send=HttpSenderOverHTTP@49e6a94d(req=QUEUED,snd=COMPLETED,failure=null)[HttpGenerator@3de6b31e{s=START}],recv=HttpReceiverOverHTTP@72ae0fc1(rsp=IDLE,failure=null)[HttpParser{s=CLOSED,0 of -1}]]
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.earlyEOF(HttpReceiverOverHTTP.java:338)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1551)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.shutdown(HttpReceiverOverHTTP.java:209)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.process(HttpReceiverOverHTTP.java:147)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.receive(HttpReceiverOverHTTP.java:73)
	at org.eclipse.jetty.client.http.HttpChannelOverHTTP.receive(HttpChannelOverHTTP.java:133)
	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.onFillable(HttpConnectionOverHTTP.java:155)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:786)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:743)
	... 1 more
```

**Comment by kaij** [comment] 2019-06-09 21:23
Update: I actually found a workaround for my use case (Http Source sitting on the same server in docker engine). By turning off keep alive on the http source server (KeepAlive Off), everything works as expected (!). Of course, this only makes sense for this special use case and you may not even have access to the source server. 

If turning off keepalive is not an option, It might be worth trying to configure the source server with http2 and see whether this works.

**Comment by adolski** [comment] 2019-06-18 18:47
Between this ticket and #289 there may be 3 or 4 different problems ongoing with the Jetty client. :smile:

I think the Jetty client situation is becoming intolerable, and HttpSource will have to use a different client, but I'm reluctant to change it on the 4.1 branch. But 5.0 is still a long way away, so maybe there is no alternative...

**Comment by adolski** [comment] 2019-06-20 15:36
There is now an HttpSource2 on the `release/4.1` branch. It uses the same configuration keys and delegate method as HttpSource, but is backed by an [OkHttp](http://square.github.io/okhttp/) client instead of Jetty. OkHttp has already been used by S3Source for some time with no issues that I'm aware of.

Please try out HttpSource2 and report any issues. If all goes well, it will replace the Jetty-backed HttpSource in 5.0.

**Comment by whikloj** [comment] 2020-02-13 14:12
Just to get in on the fun, I am also getting this error. However mine is reported as a ConnectionTimeout. 
```
2020-02-13 07:11:17,460 DEBUG [qtp1020391880-215896] e.i.l.c.s.HttpSource [HttpSource.java:489] ExecutionException from Request.send(); generating AccessDeniedException.
java.util.concurrent.ExecutionException: java.net.SocketTimeoutException: Connect Timeout
        at org.eclipse.jetty.client.util.FutureResponseListener.getResult(FutureResponseListener.java:118)
        at org.eclipse.jetty.client.util.FutureResponseListener.get(FutureResponseListener.java:101)
        at org.eclipse.jetty.client.HttpRequest.send(HttpRequest.java:711)
        at edu.illinois.library.cantaloupe.source.HttpSource.request(HttpSource.java:487)
        at edu.illinois.library.cantaloupe.source.HttpSource.request(HttpSource.java:458)
        at edu.illinois.library.cantaloupe.source.HttpSource.fetchHEADResponseInfo(HttpSource.java:433)
        at edu.illinois.library.cantaloupe.source.HttpSource.checkAccess(HttpSource.java:259)
        at edu.illinois.library.cantaloupe.resource.iiif.v2.InformationResource.doGET(InformationResource.java:108)
        at edu.illinois.library.cantaloupe.resource.HandlerServlet.handle(HandlerServlet.java:98)
        at edu.illinois.library.cantaloupe.resource.HandlerServlet.doGet(HandlerServlet.java:36)
```

Though any non-Cantaloupe request to the same URL works fine and a restart of Cantaloupe clears it up for a while.

I am running Cantaloupe 4.1.5 and just switched to use the `HttpSource2` but as this normally takes a bit of time to present, I'll monitor for now.

**Comment by DiegoPino** [comment] 2020-03-10 22:28
Hi, reporting that `HttpSource2` solved the handshake/dropped connection issues (and the day!) we had between Cantaloupe and our SSL exposed Image Source Server. 

When dealing only with `http`, errors where mostly random (on high load) but when accessing the images via SSL we were hitting `java.io.EOFException` the whole time. I saw a few Jetty client Threads where the suggested solution was to limit the number of concurrent connection on the client  side to only 2 (still buggy IMHO). Just in case someone wants to test that or still believes Jetty Client can be saved.

Also, in case someone hits this. When using an HTTPS image source, Jetty was able to read global certs from `$JAVA_HOME/jre/lib/security/cacerts`, but  `OkHttp` insisted on using only `Djavax.net.ssl.trustStore` and ignored the global JVM one. No expert at all, but i found it strange. In case someone hits `PKIX path building failed unable to find valid certification path` when accessing an `info.json` and does not know what/how that came from after moving from one source to another. 

Thanks @adolski for giving us HttpSource2!

**Comment by adolski** [comment] 2020-04-17 20:22
Thanks for the feedback, @DiegoPino. Just curious how you fixed the cert issue with OkHttp? Did you set `javax.net.ssl.trustStore` to `$JAVA_HOME/jre/lib/security/cacerts`?

**Comment by DiegoPino** [comment] 2020-04-21 20:55
@adolski sorry, this went under my radar. 
We decided to point `Djavax.net.ssl.trustStore=` to our own maintained truststore file (we are using tomcat). Makes also more sense for us and keeps things also more portable in case of a system wide Java update since (kinda obvious but i was not aware of) because $JAVA_HOME/jre/lib/security/cacerts got reset magically to `defaults` on larger package upgrade while i was doing tests. 
I guess you could point it to $JAVA_HOME/jre/lib/security/cacerts? Since our local and that one, both, are managed in the same way via `keytool`. But i have not tested that approach.

**Comment by adolski** [comment] 2021-04-09 21:42
Well, there haven't been any complaints about HttpSource2 yet. So, in 4.1.x, I'd recommend just moving over to that.

In 5.0, HttpSource2 is now known as HttpSource and the old Jetty-backed HttpSource has been removed. So I'm going to just close this.

**Closed by adolski** 2021-04-09 21:42 UTC
