### ISSUE TITLE
Source caching requires chunking disabled

### ISSUE THREAD

**Issue by Geoffsc** [cantaloupe-project/cantaloupe#290] opened 2019-06-05 13:55 UTC
- In ProcessorConnector.java line 217, if streamFactory.isSeekingDirect() is true then the RetrievalStrategy.CACHE option never gets hit. The RetrievalStrategy.CACHE option handles source caching.
- In HTTPStreamFactory.java line 110, isSeekingDirect() returns isChunkingEnabled(). So source caching only works if HttpSource.chunking.enabled = false in cantaloupe.properties. HttpSource.chunking.enable = true by default.

This is not mentioned anywhere in the caching documentation:
https://cantaloupe-project.github.io/manual/4.1/caching.html

Is this a bug or a documentation issue or something else?

**Comment by demiankatz** [comment] 2019-06-06 13:26
This issue required several hours of research and code review to resolve -- we couldn't understand why the cache was never populated in spite of being enabled as described in the documentation -- so if it's not a bug, it at least requires better documentation to help others in the future! We can contribute to a pull request if that would help, but wanted to be sure we were taking the most appropriate approach before putting something together.

**Comment by adolski** [comment] 2019-06-17 19:24
This was an oversight. ProcessorConnector is correctly asking the Source about its seeking support, but it fails to ask the Processor about whether it will want to use that support -- it assumes it will, but for non-selectively-readable source formats, [it assumes wrong](https://github.com/cantaloupe-project/cantaloupe/blob/8508e9353be4597153fff8298d8b43508808c76c/src/main/java/edu/illinois/library/cantaloupe/processor/codec/AbstractIIOImageReader.java#L306).

Will push a fix soon.

**Comment by demiankatz** [comment] 2019-06-17 19:29
Thanks for the update and analysis, @adolski!

**Comment by Geoffsc** [comment] 2019-06-17 21:47
Yes, thanks much :)

**Comment by adolski** [comment] 2019-06-18 14:56
This should be fixed now--will appear in 4.1.3. Also, I added a note about this situation (not the bug, but the overall idea of how chunking can override the source cache) in the caching section of the manual: https://github.com/cantaloupe-project/cantaloupe-project.github.io/blob/caf987b60bc7da6f8d9ef6259f290a2d7ad8f8b1/manual/4.1/caching.html#L83

**Closed by adolski** 2019-06-18 14:56 UTC
Labels: bug
