### ISSUE TITLE
JPEG2000KakaduImageReader errors in Kakadu Region Decompressor

### ISSUE THREAD

**Issue by ebenenglish** [cantaloupe-project/cantaloupe#300] opened 2019-07-24 20:48 UTC
Fairly new to Cantaloupe, we are attempting to use it with JPEG2000 source images.

Most of the time, it works great! However, we are getting errors on _certain_ images when attempting to view in OpenSeadragon:
```
Error in Kakadu Region Decompressor:
The `region' passed into `kdu_region_decompressor::start' does not lie fully
within the region occupied by the full image on the rendering canvas.
```
When this occurs, it _crashes_ Cantaloupe, and the application has to be restarted.

We're using Cantaloupe 4.1 on Linux 18.04, using the Kakadu binaries/libraries supplied in `deps/Linux-x86-64`.

Full error message from logs:
```
2019-07-24 15:06:34,656 INFO [qtp1531333864-2556] e.i.l.c.r.i.v.ImageResource [AbstractResource.java:109] Handling GET /iiif/2/commonwealth:1257b807z/8192,0,310,4096/78,/0/default.jpg

2019-07-24 15:06:34,841 ERROR [qtp1531333864-5490] e.i.l.c.p.c.JPEG2000KakaduImageReader [JPEG2000KakaduImageReader.java:157] Error in Kakadu Region Decompressor:
The `region' passed into `kdu_region_decompressor::start' does not lie fully
within the region occupied by the full image on the rendering canvas.  The
error is probably connected with a misunderstanding of the way in which
codestream dimensions are mapped to rendering coordinates through the rational
upsampling process offered by the `kdu_region_decompressor' object.  It is best
to use `kdu_region_decompressor::get_rendered_image_dims' to find the full
image dimensions on the rendering canvas.
```

For examples of offending image files, see:
* https://fedoradev.bpl.org/fedora/objects/bpl-dev:gq67jr234/datastreams/accessMaster/content
* https://fedoradev.bpl.org/fedora/objects/bpl-dev:gq67jr19j/datastreams/accessMaster/content

Any ideas on how to troubleshoot would be greatly appreciated. Thanks!

**Comment by adolski** [comment] 2019-07-24 21:27
Hi @ebenenglish ,

This has been bothing me too. There is an attempted fix in 4511f41cad639d0f141c7d4357e6313fff064f5c (`release/4.1` branch) but I haven't confirmed whether it works yet.

**Comment by adolski** [comment] 2019-07-25 14:22
Nope, but the above commit should be a fix.

**Comment by ebenenglish** [comment] 2019-07-25 21:55
Hi @adolski, thanks for taking a look at this so quickly! Are you planning to cut a 4.1.3 release soon?

I downloaded the `develop` branch, and ran `$ mvn clean package -DskipTests` to create a new .war file, which was create at `./target/cantaloupe-5.0-SNAPSHOT.war`. I'm attempting to use this, and was able to successfully get the Cantaloupe admin interface to load.

However, now I'm getting this error when trying to view _any_ JPEG2000:
```
2019-07-25 17:50:15,133 INFO [qtp884457408-14] e.i.l.c.r.i.v.ImageResource [AbstractResource.java:100] Handling GET /iiif/2/bpl-dev:rn301174j/full/164,/0/default.jpg
2019-07-25 17:50:15,686 ERROR [qtp884457408-15] e.i.l.c.p.c.j.JPEG2000KakaduImageReader [JPEG2000KakaduImageReader.java:159] Kakadu Core Error:
You may not apply restrictions to the resolution or number of image components
after the first tile access, unless the codestream object is set up to be
persistent.
```
Any advice or recommendations would be greatly appreciated, thanks!

**Comment by adolski** [comment] 2019-07-25 22:37
Hi @ebenenglish ,

You should probably be on the `release/4.1` branch unless you are very brave. From that branch you can build 4.1.3-SNAPSHOT.

I don't have a date for 4.1.3, but probably in the next few weeks. 

Not sure what that error is, but will look into it as time permits.

**Comment by ebenenglish** [comment] 2019-07-25 23:12
Cool, I'll try and build from the `release/4.1` branch. If that error ("You may not apply restrictions to the resolution or number of image components") shows up after I try and run that build, I'll let you know. Thanks!

**Comment by ebenenglish** [comment] 2019-07-26 12:52
OK, I built from the `release/4.1` branch, and I'm able to get Cantaloupe to render tiles for JP2 images that were previously causing crashes. (Yay! Thanks again!)

Weirdly though, I'm still able to produce Region Decompressor errors and crashes on certain files. Here's an example:
https://fedoradev.bpl.org/fedora/objects/bpl-dev:tt44pn102/datastreams/accessMaster/content

In my tests, this is the only image (so far) that still causes a crash. If I find others I will post a link to them here.

**Comment by adolski** [comment] 2019-07-26 13:29
I can't access that URL (firewalled?)

**Comment by ebenenglish** [comment] 2019-07-27 17:11
Sorry @adolski, forgot those links were inaccessible outside our network.

Here is a link to the image still causing the Region Decompressor error:
https://fedora.digitalcommonwealth.org/fedora/objects/commonwealth:1257b807z/datastreams/accessMaster/content

So far I haven't been able to find any other images causing the error, but will let you know if I do.

BUT, now that we're running `4.1.3-SNAPSHOT.war`, we're getting a fair amount of the `You may not apply restrictions to the resolution or number of image components
after the first tile access` errors I mentioned earlier.

Here's the full error message again:
```
2019-07-26 13:47:02,583 INFO [qtp920011586-2406] e.i.l.c.r.i.v.ImageResource [AbstractResource.java:109] Handling GET /iiif/2/commonwealth:rj430x08g/0,0,4096,4026/1024,/0/default.jpg
2019-07-26 13:47:03,072 ERROR [qtp920011586-2406] e.i.l.c.p.c.JPEG2000KakaduImageReader [JPEG2000KakaduImageReader.java:157] Kakadu Core Error:
You may not apply restrictions to the resolution or number of image components
after the first tile access, unless the codestream object is set up to be
persistent.
```
Here are links to some images causing this error:
https://fedora.digitalcommonwealth.org/fedora/objects/commonwealth:rj430x08g/datastreams/accessMaster/content
https://fedora.digitalcommonwealth.org/fedora/objects/ccommonwealth:r781xk524/datastreams/accessMaster/content

Let me know if you'd prefer to open a separate issue for this problem?

Thanks again, I _really_ appreciate your help with this.

**Comment by bbarberBPL** [comment] 2019-07-29 20:33
Hello @adolski  I'm @ebenenglish 's colleague. I was able to find a core dump file when the java vm crashed with ALL of the details of when it crashes the java VM. Hopefully this will help you further debug with this.  This is also from the 4.1.3-SNAPSHOT build. Doesn't seem to happen as frequently as Eben described above, but it still happens enough to be concerned. 

[cantaloupe_core_dump_issue_300.txt](https://github.com/cantaloupe-project/cantaloupe/files/3444164/cantaloupe_core_dump_issue_300.txt)

**Comment by adolski** [comment] 2019-07-29 21:48
Thanks for posting all of that stuff, @ebenenglish and @bbarberBPL . This bug is caused by me misunderstanding how the `kdu_region_decompressor` is supposed to work when using resolution level selection in conjunction with expansion (a.k.a. scaling). Given the feedback about the last commit, I think I know generally what's wrong. I'm testing a fix that is so far solving ~99% of the crashes, but there is still a math bug that appears at certain scales (particularly around resolution level boundaries) that I'm trying to track down in order to solve the remaining 1%.

**Comment by adolski** [comment] 2019-07-30 14:44
I think I was making things more complicated than they needed to be. 9dd20b4 was the wrong approach, so I reverted that and also removed the bounds check, which could trigger unnecessarily.

Then, I tested against every integer width in the image you shared, using fit-to-width URI syntax (e.g. `/full/w,/0/default.jpg`), and there were no failures. (Before, I saw them at `2134,`, `4254,`, `4255,`, `4256,`, `4257,`,... I stopped there.)

I also tested against a couple of other images that I found this happening with on my own, and those were fine too.

(It might be nice to have automated tests for this, but they would take a long time to run.)

So, as of now, I'm not able to produce any more crashes or HTTP 500s...

**Comment by bbarberBPL** [comment] 2019-07-30 14:55
Great! Ill rebuild this and test it out in our development environment. Ill let you know if everything is good.

**Comment by bbarberBPL** [comment] 2019-07-30 15:48
@adolski  So, good and bad news. I checked on my dev environment and it appears those changes worked for most of the images. However the image at the link below is proving problematic since as soon as it loads in the viewer its causes a core dump similar to the one I shared above, the same problematic frame is shown.
Here is the image/
https://fedoradev.bpl.org/fedora/objects/bpl-dev:gq67jr19j/datastreams/accessMaster/content.


Also the  last two iiif urls the viewer calls, once it opens, are causing it to crash the JVM. Not sure which one is causing it. 
... /4096,0,321,4096/81,/0/default.jpg
.../4096,4096,321,1540/81,/0/default.jpg

I really appreciate you looking into this.

**Comment by adolski** [comment] 2019-07-30 15:58
Hi @bbarberBPL, that URL times out for me.

**Comment by bbarberBPL** [comment] 2019-07-30 16:02
Sorry about that forgot about the firewall here it is. I had to zip it since its a jp2 file and github doesn't support those. 

[0000_1506_56.jp2.zip](https://github.com/cantaloupe-project/cantaloupe/files/3447639/0000_1506_56.jp2.zip)

**Comment by adolski** [comment] 2019-07-30 20:50
Thanks. I was able to reproduce the crash on the `/4096,4096,321,1540/81,/0/default.jpg` request.

I think there is a bug in the kdu_region_decompressor that causes misalignment between the ROI and the image canvas in some cases (like this one), which then causes a crash. (Or, maybe it's not a bug and I'm still doing something wrong, but I don't know what.) I added a little hack to try to work around this, which fixes this crashing request, and doesn't break any of the tests.

I'm sorry to throw the ball back into your court on testing, but I don't really have a collection of crashing images on my end.

**Comment by bbarberBPL** [comment] 2019-07-30 20:52
No worries I will give that patch a try and see what happens on my end. I will also provide you with more images that break if i find any.

**Comment by bbarberBPL** [comment] 2019-07-31 13:54
@adolski  So pulled those recent changes and the images are opening properly now without a core dump.  Problem is once I start to zoom for some of them in the viewer it break again.  I'm attaching a zip with 3 bad images and one that didn't break(06_01_006224(1).jp2). The one I sent you earlier also doesn't break either when zooming. I also added a txt file with the file names and the urls they seem to have broken on. Finally I added the recent core dump log (hs_err_pid17132.log) in case that helps. 
[cantaloupe_413_bad_images.zip](https://github.com/cantaloupe-project/cantaloupe/files/3452149/cantaloupe_413_bad_images.zip)
[06_01_006224 (1).jp2.zip](https://github.com/cantaloupe-project/cantaloupe/files/3452157/06_01_006224.1.jp2.zip)

**Comment by adolski** [comment] 2019-07-31 21:23
Knock on wood, but I'm pretty confident that this is fixed now... not confident enough to click the close button, but still pretty confident.

**Comment by bbarberBPL** [comment] 2019-08-01 13:21
Looks like we have a winner! None of the previous images are crashing after I tested zooming/rotating etc in the viewer.  Not seeing any core dump logs now either. You can go ahead and click complete now. If anything comes up. I leave a comment here but overall looks like its working now

**Comment by adolski** [comment] 2019-08-01 15:42
5th time's a charm. Thanks for reporting this, and all of your assistance in getting it fixed.

**Closed by adolski** 2019-08-01 15:42 UTC
Labels: bug

**Comment by bbarberBPL** [comment] 2019-08-02 14:12
@adolski  I spoke too soon I'm afraid.  I came in this morning only to find more core dump logs on the server after wiping the previous ones. The same consistent line as before appeared in all the new ones.

`Problematic frame:
 C  [libkdu_jni.so+0x2345ca]  kdu_supp::kdu_region_decompressor::process(int*, kdu_core::kdu_coords, int, int, int, kdu_core::kdu_dims&, kdu_core::kdu_dims&)+0xda
`
However The error logs showed a new error message being thrown.

`2019-08-02 09:42:23,948 ERROR [qtp920011586-58] e.i.l.c.p.c.JPEG2000KakaduImageReader [JPEG2000KakaduImageReader.java:157] Kakadu Core Error:
You may not apply restrictions to the resolution or number of image components
after the first tile access, unless the codestream object is set up to be
persistent.`

I'm going to attach two more images plus a text file with the log snippets for you. The image names match the identifiers in the urls of the log snippets FYI

Side note I've also seen alot of errors like this in tandem with the above one. Seems to be related to getting the info.json file. 

`2019-08-02 06:56:12,319 ERROR [qtp920011586-503] e.i.l.c.r.ImageRepresentation [ImageRepresentation.java:94] Failed to read from FilesystemCache: null
org.eclipse.jetty.io.EofException: null
	at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:286)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.flush(SslConnection.java:882)
	at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:393)
	at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:277)
	at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:380)
	at org.eclipse.jetty.server.HttpConnection$SendCallback.process(HttpConnection.java:802)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
	at org.eclipse.jetty.server.HttpConnection.send(HttpConnection.java:538)
	at org.eclipse.jetty.server.HttpChannel.sendResponse(HttpChannel.java:831)
	at org.eclipse.jetty.server.HttpChannel.write(HttpChannel.java:887)
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:239)
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:215)
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:514)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1793)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1769)
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:1744)
	at edu.illinois.library.cantaloupe.resource.ImageRepresentation.write(ImageRepresentation.java:87)
	at edu.illinois.library.cantaloupe.resource.iiif.v2.ImageResource.doGET(ImageResource.java:213)
	at edu.illinois.library.cantaloupe.resource.HandlerServlet.handle(HandlerServlet.java:98)
	at edu.illinois.library.cantaloupe.resource.HandlerServlet.doGet(HandlerServlet.java:36)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:857)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:535)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1340)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1242)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:503)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ssl.SslConnection$1.run(SslConnection.java:144)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.base/java.lang.Thread.run(Thread.java:835)
Caused by: java.io.IOException: Broken pipe
	at java.base/sun.nio.ch.FileDispatcherImpl.write0(Native Method)
	at java.base/sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
	at java.base/sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:113)
	at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:79)
	at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:50)
	at java.base/sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:466)
	at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:264)
	... 47 common frames omitted`
 
[cantaloupe-413-badimg2.zip](https://github.com/cantaloupe-project/cantaloupe/files/3461585/cantaloupe-413-badimg2.zip)

**Comment by adolski** [comment] 2019-08-02 15:23
Hi @bbarberBPL,

I can't reproduce the JP2 errors on my end. But, judging by the messages, I think they are different from the other one this issue. Can you create a new issue for these?

The FilesystemCache thing I'm not sure is an error -- the cause being a broken pipe IOException which usually happens when the client closes the connection before the response has been fully sent. Although, one could argue that this shouldn't be logged at error level...
